version: '2.1'

services:
  authentication-service:
    image: "698990599346.dkr.ecr.us-east-1.amazonaws.com/authentication-service:latest"
    container_name: "authentication-service"
    environment:
      AWS_COGNITO_CLIENT_ID: 6ci3qn66kp1pnjonkdmk19smet
      AWS_COGNITO_CLIENT_SECRET: 1bqm3d6u7akafnaveid24atgcpfkbb7d34ec7a31n7ob7o28s6qf
      AWS_SESSION_REGION: us-east-1

  user-service:
    image: "698990599346.dkr.ecr.us-east-1.amazonaws.com/user-service:latest"
    container_name: "user-service"
    environment:
      - PROTOCOL=http
      - HOST=localhost
      - PORT=3000
      - CASSANDRA_KEYSPACE=user
      - CASSANDRA_SERVICE_HOST=localhost
      - CASSANDRA_SERVICE_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra

###################################
### Infrastructure Dependencies ###
###################################
  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - 4171:4171

  cassandra:
    container_name: local-cassandra
    image: cassandra:3.9
    ports:
      - 9042:9042
    volumes:
      - ~/data/cassandra/local-env:/var/lib/cassandra/

  # elastic:
  #   container_name: elastic
  #   image: elasticsearch:5.1.1
  #   command: elasticsearch -E cluster.name='local' -E network.host='local-elastic' -E network.bind_host='0.0.0.0'
  #   volumes:
  #     - ~/data/elastic/local-env:/user/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
